### ISSUE TITLE
Edit Mode Button is missing

### ISSUE THREAD

**Issue by Katzenhirn** [GoldpawsStuff/BigGameMenu#5]
![WoWScrnShot_121222_103518](https://user-images.githubusercontent.com/70470937/207011609-96f47d68-90bb-4000-8f44-c31e4072d586.jpg)

Since a few days the "Editmode" button is missing. Even with all other addons disabled it won't show up again.

**Comment by migwynkriid** [comment]
Same issue for me.

**Comment by DygDyg** [comment]
There is also no edit mode button
